name: devops
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: mysecretpassword
          POSTGRES_DB: devops
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.11.0'

      - name: Install dependencies
        run: npm install

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done

      - name: Load environment variables
        run: |
          cat .env >> $GITHUB_ENV

#      - name: Export environment variables
#        run: |
#          echo "DATABASE_HOST=localhost" >> $GITHUB_ENV
#          echo "DATABASE_PORT=5432" >> $GITHUB_ENV
#          echo "DATABASE_USER=postgres" >> $GITHUB_ENV
#          echo "DATABASE_PASSWORD=mysecretpassword" >> $GITHUB_ENV
#          echo "DATABASE_DB=devops" >> $GITHUB_ENV
#          echo "DATABASE_SYNCHRONIZE=true" >> $GITHUB_ENV

      - name: Build code
        run: npm run build

      - name: Run tests
        run: npm run test:e2e
