name: devops
on: 
  push:
    branches:
      - master
jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node js
      uses: actions/setup-node@v2
      with:
        node-version: '18.16.0'
    - name: Install dependencies
      run: npm install
    - name: Build code
      run: npm run build
    - name: Run tests
      run: npm run test:e2e
      
      
      
