name: devops
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        options: >-
          --health-cmd="pg_isready -U ${{ secrets.POSTGRES_USER }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:  # Set permanent environment variables
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USER: ${{ secrets.POSTGRES_USER }}
      DATABASE_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      DATABASE_DB: ${{ secrets.POSTGRES_DB }}
      DATABASE_SYNCHRONIZE: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.11.0'

      - name: Install dependencies
        run: npm install

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h $DATABASE_HOST -p $DATABASE_PORT -U $DATABASE_USER; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done

      - name: Build code
        run: npm run build

      - name: Run tests
        run: npm run test:e2e
